//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessAudiobooks_UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/usr/bin/m4b-tool merge --adjust-for-ipod --jobs=32 --ffmpeg-threads=16 --force -" +
            "-name=\"%Name%\" --artist=\"%Artist%\" --album=\"%Album%\" --year=\"%Year%\" --genre=\"%G" +
            "enre%\" --writer=\"%Writer%\" \'./\' --output-file=\"%outputName%\"")]
        public string remoteCommand {
            get {
                return ((string)(this["remoteCommand"]));
            }
            set {
                this["remoteCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sshConnectDetails {
            get {
                return ((string)(this["sshConnectDetails"]));
            }
            set {
                this["sshConnectDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string localPath {
            get {
                return ((string)(this["localPath"]));
            }
            set {
                this["localPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string remotePath {
            get {
                return ((string)(this["remotePath"]));
            }
            set {
                this["remotePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string overrideOutputDirectory {
            get {
                return ((string)(this["overrideOutputDirectory"]));
            }
            set {
                this["overrideOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool overrideOutputDirectoryBool {
            get {
                return ((bool)(this["overrideOutputDirectoryBool"]));
            }
            set {
                this["overrideOutputDirectoryBool"] = value;
            }
        }
    }
}
